### ISSUE TITLE
Package six is missing after installation

### ISSUE THREAD

**Issue by chbndrhnns** [dougn/python-plantuml#11]
Installing the package with `pip install plantuml`  and afterwards running it with `python -m plantuml` fails due to the missing `six` package which needs to be installed manually:

```bash
python -m plantuml
\Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/plantuml.py", line 13, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

**Comment by jacebrowning** [comment]
I think `'six'` needs to be added to `install_requires`.
