### ISSUE TITLE
install fail if httplib2 is not already installed

### ISSUE THREAD

**Issue by perrinjerome** [dougn/python-plantuml#12]
Because `setup.py` imports from `plantuml.py` and `plantuml.py` imports `httplib2`, executing setup script fails if `httplib2` is not already installed:

```
$ python3 -m venv tempenv

$ ./tempenv/bin/pip install git+https://github.com/SamuelMarks/python-plantuml#egg=plantuml
Collecting plantuml
  Cloning https://github.com/SamuelMarks/python-plantuml to ./pip-install-_wq8frrt/plantuml
  Running command git clone -q https://github.com/SamuelMarks/python-plantuml /tmp/pip-install-_wq8frrt/plantuml
    ERROR: Command errored out with exit status 1:
     command: /tmp/tempenv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_wq8frrt/plantuml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_wq8frrt/plantuml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-_wq8frrt/plantuml/pip-egg-info
         cwd: /tmp/pip-install-_wq8frrt/plantuml/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_wq8frrt/plantuml/setup.py", line 2, in <module>
        from plantuml import __author__, __version_string__, __email__
      File "/tmp/pip-install-_wq8frrt/plantuml/plantuml.py", line 12, in <module>
        import httplib2
    ModuleNotFoundError: No module named 'httplib2'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by perrinjerome** [comment]
This is same as https://github.com/dougn/python-plantuml/issues/2 , but the problem is still there.
