### ISSUE TITLE
Installing plantuml fails if httplib2 is not already installed

### ISSUE THREAD

**Issue by tuomas2** [dougn/python-plantuml#2]
```
pip install plantuml==0.1
Downloading/unpacking plantuml==0.1
  Downloading plantuml-0.1.0.tar.gz
  Running setup.py (path:/home/tairaksinen/.virtualenvs/automate_test/build/plantuml/setup.py) egg_info for package plantuml
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/tairaksinen/.virtualenvs/automate_test/build/plantuml/setup.py", line 2, in <module>
        import plantuml
      File "plantuml.py", line 4, in <module>
        import httplib2
    ImportError: No module named httplib2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/tairaksinen/.virtualenvs/automate_test/build/plantuml/setup.py", line 2, in <module>

    import plantuml

  File "plantuml.py", line 4, in <module>

    import httplib2

ImportError: No module named httplib2

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/tairaksinen/.virtualenvs/automate_test/build/plantuml
Storing debug log for failure in /home/tairaksinen/.pip/pip.log
```

Suggestion: use something like this instead of import:

```
def get_version(filename):
    with open(filename) as fh:
        metadata = dict(re.findall("__([a-z]+)__ = '([^']+)'", fh.read()))
        return metadata['version']
```

**Comment by dougn** [comment]
the requirements.txt should be installed for development and building.
