### ISSUE TITLE
PlantUML Error when PlantUML file has an include file ('PlantUMLHTTPError' object has no attribute 'message')

### ISSUE THREAD

**Issue by NovoLearn** [dougn/python-plantuml#23]
Hi, I'm trying to get plantuml to create an SVG from a Plant UML file that has a file include in it

Example Plant UML File: `my_yaml_file.puml`:
```
@startyaml my_yaml_file.yml
title my_yaml_file.yml
!include /path/to/my_yaml_file.yml
@endyaml
```

When plantuml sends to the file to PlantUML server to create a diagram as SVG file, the following error message is returned:
`ERROR - Error generating diagram my_daigram_name.svg: 'PlantUMLHTTPError' object has no attribute 'message'`

The PlantUML Server url for the SVG file creation is: `http://my_local_plantUML_server_url/SVG/ENCODED`.

Anything that I'm doing wrong here, or a current limitation perhaps?

**Comment by JoachimCoenen** [comment]
I got the same error without a file include. Here's a stacktrace:
```
Error:, Traceback (most recent call last):
  [...]
  File "C:\users\Someone\Somewhere\modelGraphScript.py", line 54, in generatePlantUmlSVG
    return plantuml.PlantUML(URL_PLANTUML_SVG).processes(plantUmlText)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\users\Someone\Somewhere\.venv\Lib\site-packages\plantuml.py", line 173, in processes
    raise PlantUMLHTTPError(response, content)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\users\Someone\Somewhere\.venv\Lib\site-packages\plantuml.py", line 56, in __init__
    if not self.message:
           ^^^^^^^^^^^^
AttributeError: 'PlantUMLHTTPError' object has no attribute 'message'
```

**Comment by JoachimCoenen** [comment]
It looks like this bug has already been fixed in December 2019, but the last release is from November 2019.
the bad line now reads: `if not getattr(self, 'message', None):`.
This project does not seem to be maintained anymore. See: Issue #22.
